title: Babu Sneha
description: "Showcasing my journey and projects in Cybersecurity"
# logo: /assets/img/headshot_circle.png
# show_downloads: false
theme: jekyll-theme-cayman
url: "https://snehuh.github.io"
baseurl: ""